n_partecipants = 12;
n_trials = 115;

for i = 1:n_partecipants
    name = strcat('../../computations/collected_data/data_for_hgf_', int2str(i), '.mat');
    load(name);
    estimation = tapas_fitModel(input_cat_dog,...
        gt_cat_dog,...
        'tapas_hgf_binary_config',...
        'tapas_unitsq_sgm_config',...
        'tapas_quasinewton_optim_config');
    ideal = tapas_fitModel([],...
        gt_cat_dog,...
        'tapas_hgf_binary_config',...
        'tapas_bayes_optimal_binary_config',...
        'tapas_quasinewton_optim_config');
    omega_ideal_cat_dog = ideal.p_prc.om;
    omega_estimation_cat_dog = estimation.p_prc.om;
    estimation = tapas_fitModel(input_figures, ...
        gt_figures,...
        'tapas_hgf_binary_config',...
        'tapas_unitsq_sgm_config',...
        'tapas_quasinewton_optim_config');
    ideal = tapas_fitModel([],...
        gt_figures,...
        'tapas_hgf_binary_config',...
        'tapas_bayes_optimal_binary_config',...
        'tapas_quasinewton_optim_config');
    omega_ideal_figures = ideal.p_prc.om;
    omega_estimation_figures = estimation.p_prc.om;
    estimation = tapas_fitModel(input_sounds,...
        gt_sounds,...
        'tapas_hgf_binary_config',...
        'tapas_unitsq_sgm_config',...
        'tapas_quasinewton_optim_config');
    ideal = tapas_fitModel([],...
        gt_sounds,...
        'tapas_hgf_binary_config',...
        'tapas_bayes_optimal_binary_config',...
        'tapas_quasinewton_optim_config');
    omega_ideal_sounds = ideal.p_prc.om;
    omega_estimation_sounds = estimation.p_prc.om;
    name = strcat('../../computations/collected_data/fitted/collected_data_fitted_', int2str(i), '.mat');
    save(name, 'omega_ideal_cat_dog', 'omega_estimation_cat_dog', 'omega_ideal_figures', ...
        'omega_estimation_figures', 'omega_ideal_sounds', 'omega_estimation_sounds', 'n_mistakes', );
end